<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="51" started-at="2018-12-20T09:21:32Z" finished-at="2018-12-20T09:21:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="51" started-at="2018-12-20T09:21:32Z" finished-at="2018-12-20T09:21:32Z">
      <class name="testngGroups.TestDependency">
        <test-method status="FAIL" signature="serverStartedOk()[pri:0, instance:testngGroups.TestDependency@86be70a]" name="serverStartedOk" duration-ms="11" started-at="2018-12-20T09:21:32Z" finished-at="2018-12-20T09:21:32Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at testngGroups.TestDependency.serverStartedOk(TestDependency.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- serverStartedOk -->
        <test-method status="PASS" signature="Depend()[pri:0, instance:testngGroups.TestDependency@86be70a]" name="Depend" duration-ms="1" started-at="2018-12-20T09:21:32Z" depends-on-methods="testngGroups.TestDependency.serverStartedOk" finished-at="2018-12-20T09:21:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Depend -->
      </class> <!-- testngGroups.TestDependency -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
